language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gfortran

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    - RUSTDOC_VERSION=nightly
    - secure: XKSsYKtC/Zz+CBRmjk7qevXSXmuL9xHWviQrYEkh/69nZDLVGQSPRQSJLoyNXwBiAN26MSl2GRA8+cL+VasF5GbK1z/otUORGWeSxXXUgWb9bG/JPPwZNA/NpbaaHHfokJOkPLppCl6W8S/u2CcAKKx/1xDzvfqqD3AGvEnwjyr6hsKpOjwpHVJ+7E96RqnepT7yklkPC4mMNhIatksRCOtIEfIAn1+qCVQrE1zGrCZ6U13cp7yHeQ6xlrmaXuLLLrwEnXYD82JTYf2sMs+HR6OztwIxs/y0q8rLLJiXFGuosJofDUs9+1NALtJsyMQ+yysK3uH9vrO8ouD8bD7mU2fDz3eMS+rRJOfoAluPssMvoGQQ3J1DzUrfGgRB+Mtq0K6+m49yKBYdsS3LfzCyjIgzQxEIifRDVi/Mqqpm/I/fe7sFIrz/lYAXjWuLiw3efbp5kBme7nvvbO9t1SsDo5B/3goJMg1y3akKY4AS0OnJeiuyCS9Lh/6kXR0t1b8aBgUgzrbr+faYuy3RTMaR/yxjVjdRV+CeN/++7l/jCvLxQDDr1hnVbLj0TkNZY5tLhAHU5zWB5Gcwh+r7gOnUCMKOP46Vtg20z1ii1w/8mDsZZfzEyo5bY3OthByWqLZ2PX+2MAg/N8otu6WuvLvBCgYYV4aARPY3Fjb4NhNhCUY=

notifications:
  email: false
