language: rust
sudo: false

addons:
  apt:
    packages:
      - gfortran

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: ADK4rWz7zGKsqrw0TCB6znwcbN9zqnsMH1VzAaq4CWUHgi4V7W5EWiEoPPv+fOORd345jX0lLzF0NASc+jl8ng/A054XsG3qtgG06NbHsf0JG4xCz2r44nQRROUWR7GnJypPvhRTwy0ODgDBrFMKG5pyrcL/pFO5D9NTxvtQiL0h9S103gRq7veRn7vM2T8FMBvEqFVwD62rwWXu2+KN4663+cj/J2xo6JiVyqR/XSQg6YXw+H48/uCyzJeUhYaJygKHosG2pl5jSNrnIsGOjrPZoYWWMMJERdvAzoN8YJkwcABtfnA2b2DgH3Cri0sBhczuS0/L3J2pOo2MBOtaNuT23Fud+LYGKkAA4vhvFoHg6Lx/nzCBh+lmDh7KRh95eZ82fWeeLaRw16DetXqrtOs7fCN6HZ2F7ucYU0vHZYXIdgEn7C9H06UUKelHWLyL/KuVSMtx0UonN0RIltrpIENCnjRHZT/hL9Lv6lHSm7y9u7WduXnrfgDTFY8Avlf/PLPlIAAwnwYrxwzNFCz0sE9XtPJGZO+vkUOdTPmlf1ELi1J40jug2nxYxm0TfIbLYn6C4ySb3D7xnOQ9irRa01XmbxibUT+XpAz41fwiunB94KZ6IlDgnYlvFSizjsy3SK5p/1vMS28hXV3HtA97LAFIw/+RXb6DfsM4onPSOxU=

notifications:
  email: false
