[package]
name = "superlu"
version = "0.2.7"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/superlu"
homepage = "https://github.com/stainless-steel/superlu"
documentation = "https://stainless-steel.github.io/superlu"
description = "The package provides an interface to SuperLU."

[dependencies]
libc = "*"
matrix = { version = "0.18", default-features = false }
superlu-sys = "*"
