[package]
name = "superlu"
version = "0.2.12"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/superlu"
homepage = "https://github.com/stainless-steel/superlu"
documentation = "https://stainless-steel.github.io/superlu"
description = "The package provides an interface to SuperLU."

[dependencies]
libc = "0.2"
matrix = { version = "0.21", default-features = false }
superlu-sys = "0.2"
